name: dogwatisaw
favicon: null
layout_spectrum: 0.2369729788042605
typography_spectrum: 0.6107665076851845
title: Dog Wat I Saw
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78626502-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1319961748085916
  lightness: 0.9211444417014718
  saturation: 0.23698969394899905
  rhythmicContrast: 0.07950702775269747
purpose: []
