name: dogwatisaw
favicon: null
layout_spectrum: 0.24965
typography_spectrum: 0.6107665076851845
title: Dog Wat I Saw
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78626502-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131313'
    - '#484848'
    - '#6a6a6a'
    - '#909090'
  brandStrength: 0.375
  lightness: 0.9211444417014718
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
